### ISSUE TITLE
Initial Release Epic

### ISSUE THREAD

**Issue by JKHeadley** [cusac/mbt.guide-backend#1]
This epic should include all tasks required to release the initial version of the mbt.guide site for volunteer use.

The expected use case is that a volunteer will have a pre-defined list of youtube videos that they have been assigned to process. The volunteer should be able to easily find each video, watch the video in the app, and add segments as they watch.

Requirements are:
- [x] Volunteers can find their video via a video search (a title search would be most appropriate).
- [x] Volunteers can add segments for a video.
- [x] Segments should include a title, a start and end time, a description, and tags of high, medium, and low relevance.

This Epic will run side-by-side with the Initial Release "release" since it both are relatively small and we are experimenting with best practices in ZenHub.

For estimations with this Epic (in Milestones, etc) I am assuming that one developer can take on around 4 story points per week.
